version: "3.9"
services:
  mongodb:
    image: mongodb/mongodb-community-server
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    restart: on-failure

volumes:
  mongodb-data:
